version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: feedbackhub-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=feedbackhub
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - feedbackhub-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: feedbackhub-app
    ports:
      - "3000:3000"
    environment:
      # Production environment configuration
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      # MongoDB connection for local development
      - MONGODB_URI=mongodb://mongo:27017/feedbackhub
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - feedbackhub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo_data:

networks:
  feedbackhub-network:
    driver: bridge 